// Generated by tools/build-puzzles.js - 2026-09-21T13:31:13.133Z
window.MOG_PUZZLES = {
 "meta": {
  "title": "Would You Survive?",
  "tagline": "10 real Maze of Gains positions. One action each. Energy is your life force - reach 0 and the run ends.",
  "intro": "Every board below was recorded from a real run during Deed Season: the wind-ups, the Energy bar, the Golden Corn at stake. Pick your action, then see what actually happened.",
  "startCta": "Enter the maze",
  "note": "10 positions · ~3 minutes · real runs, real outcomes",
  "scoring": {
   "best": 2,
   "ok": 1,
   "bad": 0,
   "lethal": 0
  },
  "tiers": [
   {
    "min": 0,
    "name": "Slime Food",
    "blurb": "The floor 1 slimes end your run before you find the stairs."
   },
   {
    "min": 8,
    "name": "Pot Smasher",
    "blurb": "You know the rules but forget them at 14 Energy with two wind-ups on your tile."
   },
   {
    "min": 14,
    "name": "Floor 10 Regular",
    "blurb": "You read every wind-up before you count Golden Corn, and you reach floor 10 most runs."
   },
   {
    "min": 19,
    "name": "Jackalot Slayer",
    "blurb": "Every action was the right one, and Sir Jackalot is next."
   }
  ],
  "share": {
   "text": "Would You Survive?\n\nI survived {survived}/10 real Maze of Gains x @YieldFields_RH positions - {points}/20 points, rank {tier}.\n\nunofficial game by @flxrnc\n\nTry it:\n{url}",
   "hashtags": []
  },
  "url": "https://buildorsurvive.xyz/",
  "footer": "Positions recorded from real Maze of Gains runs during Deed Season, September 2026.",
  "credit": {
   "label": "created by Florence",
   "url": "https://x.com/flxrnc",
   "handle": "@flxrnc"
  },
  "resultHeadline": "Run Over. Here are your results.",
  "playAgain": "New run",
  "saveCard": "Copy card",
  "shareOnX": "Share on X",
  "ogTitle": "Would You Survive? - 10 real Maze of Gains positions",
  "ogDescription": "10 real Maze of Gains positions, one action each. Energy is your life force: reach 0 and the run ends. Recorded during Deed Season.",
  "heroPuzzle": "p01"
 },
 "legend": {
  "bat": {
   "name": "Bat",
   "icon": "🦇",
   "short": "30 HP. Telegraphs a dash of up to 4 tiles along its row or column, 7-10 dmg",
   "color": "#9b6bff"
  },
  "megawhipweed": {
   "name": "Large whip plant",
   "icon": "🌵",
   "short": "60 HP. Holds its ground and lashes along one marked direction, reaching up to 3 tiles, 18-20 dmg",
   "color": "#9cc21f"
  },
  "smallslime": {
   "name": "Small slime",
   "icon": "🟢",
   "short": "15 HP. Winds up a 3-5 dmg strike at an adjacent tile over 2 turns",
   "color": "#7ddc6b"
  },
  "mediumslime": {
   "name": "Orange slime",
   "icon": "🟩",
   "short": "25 HP. Winds up a 5-8 dmg strike at an adjacent tile over 1 turn",
   "color": "#4cbf3f"
  },
  "ghost1": {
   "name": "Party-hat ghost",
   "icon": "👻",
   "short": "Invulnerable. Follows slowly and blocks its tile without attacking, 0 dmg, moves every 2 turns",
   "color": "#bfe3ff"
  },
  "croaker": {
   "name": "Hat-wearing frog",
   "icon": "🐸",
   "short": "50 HP. Prepares short hops toward you, landing on you deals 12-15",
   "color": "#1f8f80"
  },
  "dragma_bat": {
   "name": "Dragma Bat",
   "icon": "🦇",
   "short": "35 HP. Telegraphs a dash of up to 10 tiles along its row or column, 10-12 dmg",
   "color": "#9c1f3a"
  },
  "dragma_skelesoldier": {
   "name": "Dragma Soldier",
   "icon": "💀",
   "short": "70 HP. Strikes its target tile and all four tiles directly beside it at once, 15-17 dmg",
   "color": "#ff5c5c"
  },
  "ghost3": {
   "name": "Hooded ghost",
   "icon": "👻",
   "short": "Invulnerable. Follows more slowly and lands heavier adjacent strikes for 8 dmg, moves every 3 turns, blocks its tile",
   "color": "#7fbbe8"
  },
  "lobcap": {
   "name": "Lobbing mushroom",
   "icon": "🍄",
   "short": "30 HP. Stays in place and throws exploding mushrooms onto tiles near you",
   "color": "#e07a10"
  },
  "skelesoldier": {
   "name": "Armored skeleton",
   "icon": "☠️",
   "short": "60 HP. Strikes its target tile and all four tiles directly beside it at once, 12-15 dmg",
   "color": "#f28b82"
  },
  "frogspawn": {
   "name": "Frog egg cluster",
   "icon": "🥚",
   "short": "80 HP. Produces blue frogs, and a shield protects it while any of its frogs is alive",
   "color": "#2aa894"
  },
  "frogglet": {
   "name": "Blue frog",
   "icon": "🐸",
   "short": "40 HP. Hops between nearby tiles, landing on you deals 8-12",
   "color": "#3fd1b8"
  },
  "skelearcher": {
   "name": "Skeleton archer",
   "icon": "🏹",
   "short": "20 HP. Fires arrows along its row or column for 12-15, then retreats",
   "color": "#d9c9b0"
  },
  "dragma_skelechump": {
   "name": "Dragma Chump",
   "icon": "💀",
   "short": "50 HP. Winds up a 12-15 dmg strike at the adjacent tile it targeted over 2 turns",
   "color": "#c93838"
  }
 },
 "puzzles": [
  {
   "id": "p07",
   "title": "The Bat Is Resting",
   "hook": "Floor 3, 70 Energy, pots all around, and the Bat on your left just attacked, so it is resting this turn.",
   "mechanic": "Free hit",
   "mechanicNote": "After an enemy attacks it rests, and a resting enemy cannot hit you. Attacking costs 0 Energy. A Bat has 30 HP and you hit for 18: two swings.",
   "floor": 3,
   "energy": 70,
   "maxEnergy": 106,
   "atk": 18,
   "weather": null,
   "items": [],
   "board": {
    "w": 11,
    "h": 9,
    "tiles": [
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2,
      2
     ],
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2
     ],
     [
      1,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      2
     ],
     [
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      2
     ],
     [
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      1
     ],
     [
      1,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      1
     ],
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2
     ],
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2
     ],
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2
     ]
    ]
   },
   "player": {
    "x": 5,
    "y": 4
   },
   "enemies": [
    {
     "type": "bat",
     "x": 4,
     "y": 4,
     "hp": 30,
     "maxHp": 30,
     "phase": "rest",
     "turns": 1,
     "target": null,
     "shield": 0
    }
   ],
   "objects": [
    {
     "type": "pot",
     "x": 5,
     "y": 2
    },
    {
     "type": "pot",
     "x": 3,
     "y": 3
    },
    {
     "type": "pot",
     "x": 4,
     "y": 2
    },
    {
     "type": "pot",
     "x": 5,
     "y": 3
    },
    {
     "type": "portal",
     "x": 3,
     "y": 2
    }
   ],
   "pickups": [
    {
     "type": "golden_corn",
     "x": 4,
     "y": 4,
     "frozen": 0
    }
   ],
   "traps": [],
   "cues": [],
   "options": [
    {
     "id": "up",
     "kind": "break",
     "label": "Smash ↑",
     "sub": "",
     "verdict": "ok",
     "dmg": 0,
     "energyAfter": 70,
     "kills": false,
     "explain": "Smashing the pot costs 0 Energy, but the Bat wakes up while you loot. Now you have a 30-HP Bat lining up dashes, for loot you could have taken after the kill."
    },
    {
     "id": "left",
     "kind": "attack",
     "label": "Attack ←",
     "sub": "HP 30",
     "verdict": "best",
     "dmg": 0,
     "energyAfter": 70,
     "kills": false,
     "explain": "Free hit while it rests: 30 to 12. Next turn it is still resting, so the second swing kills it: two turns, 0 damage, 0 Energy."
    },
    {
     "id": "right",
     "kind": "blocked",
     "label": "Right",
     "sub": "wall",
     "verdict": "blocked",
     "dmg": 0,
     "energyAfter": 70,
     "kills": false,
     "explain": "That is a wall. You do not move."
    },
    {
     "id": "down",
     "kind": "move",
     "label": "Step down",
     "sub": "",
     "verdict": "ok",
     "dmg": 0,
     "energyAfter": 69,
     "kills": false,
     "explain": "Stepping away costs 1 Energy and gives up a free hit. The Bat wakes and comes after you."
    },
    {
     "id": "pass",
     "kind": "pass",
     "label": "Wait",
     "sub": "",
     "verdict": "ok",
     "dmg": 0,
     "energyAfter": 69,
     "kills": false,
     "explain": "Pass turn costs 1 Energy and gains nothing. The Bat rests either way."
    }
   ],
   "answer": "left",
   "reality": "What actually happened: the player hit the Bat, then killed it next turn. 0 damage taken.",
   "lesson": "Hit a resting enemy first and smash pots after it is dead.",
   "_src": {
    "file": "run-cmu6vvifd007egm0ajtruo175.jsonl",
    "turn": 232,
    "floor": 3,
    "weather": null,
    "room": null
   }
  },
  {
   "id": "p05",
   "title": "Eleven HP Left",
   "hook": "Floor 5, Blizzard active, 68 Energy: the Large whip plant on your right is down to 11 HP and lashes next turn, and a Golden Corn stalk sits directly below you.",
   "mechanic": "Kill stops the attack",
   "mechanicNote": "Attacks cost 0 Energy, and if your hit kills, the enemy's wind-up never lands. 16 ATK against 11 HP is a kill. Breaking a stalk leaves a Golden Corn pickup, but it takes your turn.",
   "floor": 5,
   "energy": 68,
   "maxEnergy": 108,
   "atk": 16,
   "weather": "blizzard",
   "items": [],
   "board": {
    "w": 11,
    "h": 9,
    "tiles": [
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
     ],
     [
      1,
      1,
      1,
      1,
      0,
      0,
      0,
      0,
      1,
      1,
      1
     ],
     [
      0,
      0,
      1,
      1,
      0,
      0,
      0,
      0,
      1,
      1,
      1
     ],
     [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1
     ],
     [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1
     ],
     [
      0,
      0,
      1,
      1,
      0,
      0,
      0,
      0,
      1,
      1,
      1
     ],
     [
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
     ],
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
     ],
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2,
      2
     ]
    ]
   },
   "player": {
    "x": 5,
    "y": 4
   },
   "enemies": [
    {
     "type": "megawhipweed",
     "x": 6,
     "y": 4,
     "hp": 11,
     "maxHp": 60,
     "phase": "charge",
     "turns": 1,
     "target": {
      "x": 5,
      "y": 4
     },
     "shield": 0
    }
   ],
   "objects": [
    {
     "type": "pot",
     "x": 4,
     "y": 5
    },
    {
     "type": "crate",
     "x": 6,
     "y": 5
    },
    {
     "type": "corn_stalk",
     "x": 5,
     "y": 5
    }
   ],
   "pickups": [],
   "traps": [
    {
     "type": "spike",
     "x": 7,
     "y": 4
    }
   ],
   "cues": [
    {
     "x": 5,
     "y": 4,
     "kind": "target"
    }
   ],
   "options": [
    {
     "id": "up",
     "kind": "move",
     "label": "Step up",
     "sub": "",
     "verdict": "ok",
     "dmg": 0,
     "energyAfter": 67,
     "kills": false,
     "explain": "Safe: you leave its reach and take 0, but you spent 1 Energy to avoid a hit you could have stopped with a free kill."
    },
    {
     "id": "left",
     "kind": "move",
     "label": "Step left",
     "sub": "",
     "verdict": "bad",
     "dmg": 26,
     "energyAfter": 41,
     "kills": false,
     "explain": "Still inside reach 3. The lash lands for ~26 and you spent 1 Energy walking into it."
    },
    {
     "id": "right",
     "kind": "attack",
     "label": "Attack →",
     "sub": "kills",
     "verdict": "best",
     "dmg": 0,
     "energyAfter": 68,
     "kills": true,
     "explain": "16 ATK into 11 HP: the plant dies, the lash never lands, 0 Energy spent. The best action on the board."
    },
    {
     "id": "down",
     "kind": "break",
     "label": "Smash ↓",
     "sub": "",
     "verdict": "bad",
     "dmg": 26,
     "energyAfter": 42,
     "kills": false,
     "explain": "Breaking the stalk keeps you inside the lash: ~26 damage and Frostbite, for Golden Corn you could take one turn later."
    },
    {
     "id": "pass",
     "kind": "pass",
     "label": "Wait",
     "sub": "",
     "verdict": "bad",
     "dmg": 26,
     "energyAfter": 41,
     "kills": false,
     "explain": "Pass turn costs 1 Energy and the lash lands for ~26. Nothing gained."
    }
   ],
   "answer": "right",
   "reality": "What actually happened: the player killed it, took 0 damage, and Vampiric restored 10 Energy.",
   "lesson": "If one attack kills, attack, because the kill stops the hit for free.",
   "_src": {
    "file": "run-cmu79br5p002ygm0anq3q616l.jsonl",
    "turn": 434,
    "floor": 5,
    "weather": "blizzard",
    "room": null
   }
  },
  {
   "id": "p08",
   "title": "Pick Your Neighbor",
   "hook": "Floor 2, 63 Energy, two Orange slimes: the one up-right just attacked and is about to rest, the one two tiles right has not noticed you, and nothing hits you this turn, so where do you stand?",
   "mechanic": "Positioning",
   "mechanicNote": "An Orange slime has 25 HP and winds up in 1 turn; at ATK 12 it takes three hits. An enemy that just attacked rests next turn, which is a free hit. Two enemies taking turns winding up on one tile means you never get a free hit.",
   "floor": 2,
   "energy": 63,
   "maxEnergy": 102,
   "atk": 12,
   "weather": null,
   "items": [],
   "board": {
    "w": 11,
    "h": 9,
    "tiles": [
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
     ],
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
     ],
     [
      0,
      0,
      0,
      0,
      1,
      1,
      0,
      0,
      0,
      0,
      1
     ],
     [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1
     ],
     [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1
     ],
     [
      0,
      0,
      0,
      0,
      1,
      1,
      0,
      0,
      0,
      0,
      1
     ],
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
     ],
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2
     ],
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2,
      2
     ]
    ]
   },
   "player": {
    "x": 5,
    "y": 4
   },
   "enemies": [
    {
     "type": "smallslime",
     "x": 7,
     "y": 2,
     "hp": 15,
     "maxHp": 15,
     "phase": "idle",
     "turns": 0,
     "target": null,
     "shield": 0
    },
    {
     "type": "mediumslime",
     "x": 7,
     "y": 4,
     "hp": 25,
     "maxHp": 25,
     "phase": "idle",
     "turns": 0,
     "target": null,
     "shield": 0
    },
    {
     "type": "smallslime",
     "x": 9,
     "y": 4,
     "hp": 15,
     "maxHp": 15,
     "phase": "idle",
     "turns": 0,
     "target": null,
     "shield": 0
    },
    {
     "type": "mediumslime",
     "x": 6,
     "y": 3,
     "hp": 25,
     "maxHp": 25,
     "phase": "attack",
     "turns": 0,
     "target": {
      "x": 5,
      "y": 3
     },
     "shield": 0
    }
   ],
   "objects": [
    {
     "type": "pot",
     "x": 8,
     "y": 3
    },
    {
     "type": "pot",
     "x": 6,
     "y": 2
    },
    {
     "type": "pot",
     "x": 6,
     "y": 5
    },
    {
     "type": "crate",
     "x": 9,
     "y": 3
    },
    {
     "type": "fountain",
     "x": 0,
     "y": 2
    },
    {
     "type": "corn_stalk",
     "x": 8,
     "y": 4
    },
    {
     "type": "corn_stalk",
     "x": 9,
     "y": 5
    }
   ],
   "pickups": [
    {
     "type": "treasure",
     "x": 7,
     "y": 3,
     "frozen": 0
    }
   ],
   "traps": [],
   "cues": [],
   "options": [
    {
     "id": "up",
     "kind": "move",
     "label": "Step up",
     "sub": "",
     "verdict": "best",
     "dmg": 0,
     "energyAfter": 62,
     "kills": false,
     "explain": "Step up and you are next to slime A as it rests: two free hits while it rests, and the third kills it and stops whatever it is winding up. Slime B stays out of it."
    },
    {
     "id": "left",
     "kind": "move",
     "label": "Step left",
     "sub": "",
     "verdict": "ok",
     "dmg": 0,
     "energyAfter": 62,
     "kills": false,
     "explain": "Stepping away is safe and wastes the rest turn. You fight both later, awake."
    },
    {
     "id": "right",
     "kind": "move",
     "label": "Step right",
     "sub": "",
     "verdict": "ok",
     "dmg": 0,
     "energyAfter": 62,
     "kills": false,
     "explain": "Step between them and slime B targets your tile while A wakes up. Two slimes taking turns means no free hits, only stepping back and forth at 1 Energy a turn."
    },
    {
     "id": "down",
     "kind": "blocked",
     "label": "Down",
     "sub": "wall",
     "verdict": "blocked",
     "dmg": 0,
     "energyAfter": 63,
     "kills": false,
     "explain": "That is a wall. You do not move."
    },
    {
     "id": "pass",
     "kind": "pass",
     "label": "Wait",
     "sub": "",
     "verdict": "ok",
     "dmg": 0,
     "energyAfter": 62,
     "kills": false,
     "explain": "Pass turn costs 1 Energy and lets A finish resting without you next to it."
    }
   ],
   "answer": "up",
   "reality": "What actually happened: the player stepped right and spent the next 12 turns stepping back and forth between the two slimes. 12 Energy lost, no progress.",
   "lesson": "Never stand where two enemies take turns winding up; fight one neighbor at a time.",
   "_src": {
    "file": "run-cmu6chvxe000wgm0a7lefanhk.jsonl",
    "turn": 89,
    "floor": 2,
    "weather": null,
    "room": null
   }
  },
  {
   "id": "p09",
   "title": "The Ghost's Loot",
   "hook": "Floor 6, 60 Energy, Blizzard active: a ghost sits directly below you on top of a frozen drop, while a Bat rests two tiles to your right.",
   "mechanic": "Ghost blocks the tile",
   "mechanicNote": "Ghosts have 0 HP and are invulnerable. Nothing can be done into a ghost's tile: no attack, no pot smash, no bump to crack the ice. They move every 2-3 turns; you wait them out.",
   "floor": 6,
   "energy": 60,
   "maxEnergy": 112,
   "atk": 18,
   "weather": "blizzard",
   "items": [
    "pogo_stick"
   ],
   "board": {
    "w": 11,
    "h": 9,
    "tiles": [
     [
      2,
      2,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
     ],
     [
      2,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
     ],
     [
      2,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
     ],
     [
      2,
      1,
      1,
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      1
     ],
     [
      1,
      1,
      1,
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      0
     ],
     [
      2,
      1,
      1,
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      0
     ],
     [
      2,
      1,
      1,
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      1
     ],
     [
      2,
      1,
      1,
      1,
      1,
      1,
      0,
      0,
      1,
      1,
      1
     ],
     [
      2,
      1,
      1,
      1,
      1,
      1,
      0,
      0,
      1,
      1,
      1
     ]
    ]
   },
   "player": {
    "x": 5,
    "y": 4
   },
   "enemies": [
    {
     "type": "bat",
     "x": 7,
     "y": 4,
     "hp": 30,
     "maxHp": 30,
     "phase": "rest",
     "turns": 1,
     "target": null,
     "shield": 0
    },
    {
     "type": "ghost1",
     "x": 5,
     "y": 5,
     "hp": 0,
     "maxHp": 0,
     "phase": "idle",
     "turns": 0,
     "target": null,
     "shield": 0
    }
   ],
   "objects": [
    {
     "type": "pot",
     "x": 9,
     "y": 3
    },
    {
     "type": "crate",
     "x": 9,
     "y": 5
    },
    {
     "type": "portal",
     "x": 6,
     "y": 3
    }
   ],
   "pickups": [
    {
     "type": "treasure",
     "x": 9,
     "y": 6,
     "frozen": 0
    },
    {
     "type": "treasure",
     "x": 8,
     "y": 4,
     "frozen": 1
    },
    {
     "type": "small_energy_orb",
     "x": 5,
     "y": 5,
     "frozen": 1
    },
    {
     "type": "small_energy_orb",
     "x": 5,
     "y": 3,
     "frozen": 0
    },
    {
     "type": "treasure",
     "x": 6,
     "y": 5,
     "frozen": 1
    }
   ],
   "traps": [],
   "cues": [],
   "options": [
    {
     "id": "up",
     "kind": "move",
     "label": "Step up",
     "sub": "pick up",
     "verdict": "best",
     "dmg": 0,
     "energyAfter": 59,
     "kills": false,
     "explain": "Step up onto the energy orb: +11 Energy, out of everyone's way, and the ghost moves off the frozen drop when its turn comes."
    },
    {
     "id": "left",
     "kind": "blocked",
     "label": "Left",
     "sub": "wall",
     "verdict": "blocked",
     "dmg": 0,
     "energyAfter": 60,
     "kills": false,
     "explain": "That is a wall. You do not move."
    },
    {
     "id": "right",
     "kind": "move",
     "label": "Step right",
     "sub": "",
     "verdict": "ok",
     "dmg": 0,
     "energyAfter": 59,
     "kills": false,
     "explain": "Step toward the resting Bat: 0 damage now and a free hit next turn while it still rests. Fine, but the energy orb was right there."
    },
    {
     "id": "down",
     "kind": "break",
     "label": "Smash ↓",
     "sub": "ice under a ghost",
     "verdict": "blocked",
     "dmg": 0,
     "energyAfter": 60,
     "kills": false,
     "explain": "The ghost is standing on that frozen drop, and nothing can be done into a ghost's tile, not even a smash. The game ignores the action."
    },
    {
     "id": "pass",
     "kind": "pass",
     "label": "Wait",
     "sub": "",
     "verdict": "ok",
     "dmg": 0,
     "energyAfter": 59,
     "kills": false,
     "explain": "Pass turn costs 1 Energy for nothing. The frozen drop is not going anywhere, and neither is the ghost yet."
    }
   ],
   "answer": "up",
   "reality": "What actually happened: the player tried to smash into the ghost's tile twice, nothing happened, then took the energy orb for +11.",
   "lesson": "A ghost blocks its tile and the loot on it, so wait for it to move.",
   "_src": {
    "file": "run-cmu6azj1c001bgm0a8myx5eyb.jsonl",
    "turn": 603,
    "floor": 6,
    "weather": "blizzard",
    "room": null
   }
  },
  {
   "id": "p04",
   "title": "Spikes and a Lash",
   "hook": "Floor 5, Blizzard active: the Large whip plant on your right lashes next turn, and the spikes under you rise on the same turn.",
   "mechanic": "Rooted enemy + spikes",
   "mechanicNote": "Whip plants are rooted: they lash along one marked direction but never move. Spikes rise on alternating turns for ~8 if you stand on them. In a Blizzard a hit also applies Frostbite: your attacks cost 2 Energy for 5 turns.",
   "floor": 5,
   "energy": 92,
   "maxEnergy": 112,
   "atk": 22,
   "weather": "blizzard",
   "items": [],
   "board": {
    "w": 11,
    "h": 9,
    "tiles": [
     [
      0,
      1,
      1,
      1,
      1,
      0,
      0,
      1,
      1,
      1,
      1
     ],
     [
      0,
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1
     ],
     [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1
     ],
     [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1
     ],
     [
      0,
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1
     ],
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
     ],
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
     ],
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
     ],
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
     ]
    ]
   },
   "player": {
    "x": 5,
    "y": 4
   },
   "enemies": [
    {
     "type": "megawhipweed",
     "x": 6,
     "y": 4,
     "hp": 60,
     "maxHp": 60,
     "phase": "charge",
     "turns": 1,
     "target": {
      "x": 4,
      "y": 4
     },
     "shield": 0
    }
   ],
   "objects": [
    {
     "type": "pot",
     "x": 0,
     "y": 1
    },
    {
     "type": "pot",
     "x": 0,
     "y": 2
    }
   ],
   "pickups": [
    {
     "type": "treasure",
     "x": 0,
     "y": 4,
     "frozen": 1
    }
   ],
   "traps": [
    {
     "type": "spike",
     "x": 5,
     "y": 4
    },
    {
     "type": "spike",
     "x": 6,
     "y": 3
    },
    {
     "type": "spike",
     "x": 7,
     "y": 4
    }
   ],
   "cues": [
    {
     "x": 4,
     "y": 4,
     "kind": "target"
    }
   ],
   "options": [
    {
     "id": "up",
     "kind": "move",
     "label": "Step up",
     "sub": "",
     "verdict": "best",
     "dmg": 0,
     "energyAfter": 91,
     "kills": false,
     "explain": "Step up: off the spikes, out of the lash. 0 damage, 91 Energy, and the plant cannot follow."
    },
    {
     "id": "left",
     "kind": "move",
     "label": "Step left",
     "sub": "",
     "verdict": "bad",
     "dmg": 19,
     "energyAfter": 72,
     "kills": false,
     "explain": "One step left is still inside a Large whip plant's reach of 3. Off the spikes, but the lash lands for ~19."
    },
    {
     "id": "right",
     "kind": "attack",
     "label": "Attack →",
     "sub": "HP 60",
     "verdict": "bad",
     "dmg": 27,
     "energyAfter": 65,
     "kills": false,
     "explain": "60 HP at 22 ATK takes three hits, and meanwhile the lash (~19) and the spikes (~8) both land. ~27 lost, plus Frostbite."
    },
    {
     "id": "down",
     "kind": "blocked",
     "label": "Down",
     "sub": "wall",
     "verdict": "blocked",
     "dmg": 0,
     "energyAfter": 92,
     "kills": false,
     "explain": "That is a wall. You do not move, still on the spikes inside the lash."
    },
    {
     "id": "pass",
     "kind": "pass",
     "label": "Wait",
     "sub": "",
     "verdict": "bad",
     "dmg": 27,
     "energyAfter": 64,
     "kills": false,
     "explain": "Pass turn costs 1 Energy and you stay on rising spikes inside the lash. ~27 damage for nothing."
    }
   ],
   "answer": "up",
   "reality": "What actually happened: the player attacked the whip plant and lost 25 Energy in one turn.",
   "lesson": "A rooted enemy cannot follow you, so step out of its reach.",
   "_src": {
    "file": "run-cmu6wymuu0003gm0bsupcv9e9.jsonl",
    "turn": 526,
    "floor": 5,
    "weather": "blizzard",
    "room": null
   }
  },
  {
   "id": "p01",
   "title": "Two Soldiers, One Exit",
   "hook": "Floor 9, 24 Energy, 170 Golden Corn at stake, and two Dragma Soldiers are one turn from striking your tile: one on your left standing on an energy orb, one directly below.",
   "mechanic": "Two strikes, one tile",
   "mechanicNote": "A Dragma Soldier strikes its target tile and all four tiles directly beside it at once. Two soldiers means two strikes, and a kill stops only that soldier's strike. A hit that does not kill stops nothing.",
   "floor": 9,
   "energy": 24,
   "maxEnergy": 130,
   "atk": 20,
   "weather": null,
   "items": [
    "pogo_stick",
    "single_shot",
    "single_shot"
   ],
   "board": {
    "w": 11,
    "h": 9,
    "tiles": [
     [
      2,
      2,
      2,
      2,
      2,
      1,
      1,
      2,
      2,
      2,
      2
     ],
     [
      2,
      2,
      2,
      1,
      1,
      1,
      1,
      1,
      1,
      2,
      1
     ],
     [
      2,
      2,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
     ],
     [
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      0,
      0,
      0,
      0
     ],
     [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
     ],
     [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
     ],
     [
      2,
      2,
      0,
      0,
      0,
      1,
      1,
      0,
      0,
      0,
      0
     ],
     [
      2,
      2,
      1,
      1,
      1,
      1,
      1,
      0,
      0,
      0,
      0
     ],
     [
      2,
      2,
      2,
      1,
      1,
      1,
      1,
      1,
      0,
      0,
      1
     ]
    ]
   },
   "player": {
    "x": 5,
    "y": 4
   },
   "enemies": [
    {
     "type": "croaker",
     "x": 8,
     "y": 4,
     "hp": 50,
     "maxHp": 50,
     "phase": "attack",
     "turns": 0,
     "target": {
      "x": 8,
      "y": 4
     },
     "shield": 0
    },
    {
     "type": "dragma_bat",
     "x": 4,
     "y": 5,
     "hp": 35,
     "maxHp": 35,
     "phase": "idle",
     "turns": 0,
     "target": null,
     "shield": 0
    },
    {
     "type": "dragma_skelesoldier",
     "x": 4,
     "y": 4,
     "hp": 30,
     "maxHp": 70,
     "phase": "charge",
     "turns": 1,
     "target": {
      "x": 5,
      "y": 4
     },
     "shield": 0
    },
    {
     "type": "ghost3",
     "x": 3,
     "y": 6,
     "hp": 0,
     "maxHp": 0,
     "phase": "idle",
     "turns": 0,
     "target": null,
     "shield": 0
    },
    {
     "type": "dragma_skelesoldier",
     "x": 5,
     "y": 5,
     "hp": 70,
     "maxHp": 70,
     "phase": "charge",
     "turns": 1,
     "target": {
      "x": 5,
      "y": 4
     },
     "shield": 0
    },
    {
     "type": "dragma_bat",
     "x": 1,
     "y": 3,
     "hp": 35,
     "maxHp": 35,
     "phase": "idle",
     "turns": 0,
     "target": null,
     "shield": 0
    }
   ],
   "objects": [
    {
     "type": "pot",
     "x": 2,
     "y": 6
    },
    {
     "type": "crate",
     "x": 0,
     "y": 3
    },
    {
     "type": "crate",
     "x": 0,
     "y": 4
    },
    {
     "type": "fountain",
     "x": 8,
     "y": 3
    },
    {
     "type": "stairs",
     "x": 9,
     "y": 5
    }
   ],
   "pickups": [
    {
     "type": "large_energy_orb",
     "x": 4,
     "y": 5,
     "frozen": 0
    },
    {
     "type": "large_energy_orb",
     "x": 4,
     "y": 4,
     "frozen": 0
    },
    {
     "type": "item",
     "x": 4,
     "y": 3,
     "frozen": 0
    }
   ],
   "traps": [
    {
     "type": "spike",
     "x": 1,
     "y": 4
    }
   ],
   "cues": [
    {
     "x": 5,
     "y": 4,
     "kind": "target"
    },
    {
     "x": 3,
     "y": 4,
     "kind": "aoe"
    },
    {
     "x": 4,
     "y": 5,
     "kind": "aoe"
    },
    {
     "x": 4,
     "y": 3,
     "kind": "aoe"
    },
    {
     "x": 6,
     "y": 5,
     "kind": "aoe"
    }
   ],
   "options": [
    {
     "id": "up",
     "kind": "blocked",
     "label": "Up",
     "sub": "wall",
     "verdict": "blocked",
     "dmg": 0,
     "energyAfter": 24,
     "kills": false,
     "explain": "That is a wall. You do not move, and both strikes still cover your tile."
    },
    {
     "id": "left",
     "kind": "attack",
     "label": "Attack ←",
     "sub": "HP 30",
     "verdict": "lethal",
     "dmg": 24,
     "energyAfter": 0,
     "kills": false,
     "explain": "ATK 20 into 30 HP leaves the soldier alive on 10, so its strike still lands. Both strikes land for ~24 on 24 Energy: run over."
    },
    {
     "id": "right",
     "kind": "move",
     "label": "Step right",
     "sub": "",
     "verdict": "best",
     "dmg": 0,
     "energyAfter": 23,
     "kills": false,
     "explain": "One step right is the only tile on the board outside both strikes. 0 damage, 23 Energy, run continues."
    },
    {
     "id": "down",
     "kind": "attack",
     "label": "Attack ↓",
     "sub": "HP 70",
     "verdict": "lethal",
     "dmg": 24,
     "energyAfter": 0,
     "kills": false,
     "explain": "ATK 20 into 70 HP does not kill. Both strikes land for ~24, Energy 0, run over on floor 9."
    },
    {
     "id": "pass",
     "kind": "pass",
     "label": "Wait",
     "sub": "",
     "verdict": "lethal",
     "dmg": 24,
     "energyAfter": 0,
     "kills": false,
     "explain": "Pass turn costs 1 Energy and you stay inside both strikes. ~24 damage on 24 Energy: run over."
    },
    {
     "id": "item",
     "kind": "item",
     "label": "Single Shot ←",
     "sub": "25 dmg - the 30-HP soldier survives",
     "verdict": "lethal",
     "dmg": 24,
     "energyAfter": 0,
     "kills": false,
     "explain": "Single Shot does 25 into 30 HP: the soldier lives on 5, and a hit that does not kill stops nothing. The shot takes your turn, both strikes land for ~24 on 24 Energy, Energy 0, run over."
    }
   ],
   "answer": "right",
   "reality": "What actually happened: the player attacked the left soldier, left it on 10 HP, and took both strikes for 24. Energy 0, run over on floor 9, 170 Golden Corn lost.",
   "lesson": "When two wind-ups cover your tile, step to the tile that neither one reaches.",
   "_src": {
    "file": "run-cmu6azj1c001bgm0a8myx5eyb.jsonl",
    "turn": 1222,
    "floor": 9,
    "weather": null,
    "room": null
   }
  },
  {
   "id": "p02",
   "title": "One Kill Is Not Enough",
   "hook": "Floor 9, 14 Energy, Heatwave with Mirage active so attack charge timing is unpredictable: a Dragma Bat on your left and a Dragma Soldier directly below are both about to strike your tile.",
   "mechanic": "One kill is not enough",
   "mechanicNote": "Killing an enemy stops its attack, and only its attack. The bat is on 11 HP and you swing for 24; the soldier is on 70 HP and its strike already covers your tile.",
   "floor": 9,
   "energy": 14,
   "maxEnergy": 130,
   "atk": 24,
   "weather": "heatwave",
   "items": [],
   "board": {
    "w": 11,
    "h": 9,
    "tiles": [
     [
      2,
      2,
      0,
      0,
      0,
      0,
      0,
      2,
      2,
      2,
      2
     ],
     [
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      1,
      2,
      2,
      2
     ],
     [
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      2,
      2
     ],
     [
      1,
      1,
      1,
      1,
      0,
      0,
      1,
      1,
      1,
      2,
      2
     ],
     [
      1,
      1,
      1,
      1,
      0,
      0,
      1,
      1,
      1,
      2,
      2
     ],
     [
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      2
     ],
     [
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      2,
      2
     ],
     [
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      2,
      2
     ],
     [
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      2,
      2
     ]
    ]
   },
   "player": {
    "x": 5,
    "y": 4
   },
   "enemies": [
    {
     "type": "dragma_bat",
     "x": 4,
     "y": 4,
     "hp": 11,
     "maxHp": 35,
     "phase": "charge",
     "turns": 1,
     "target": {
      "x": 4,
      "y": 4
     },
     "shield": 0
    },
    {
     "type": "croaker",
     "x": 2,
     "y": 8,
     "hp": 50,
     "maxHp": 50,
     "phase": "idle",
     "turns": 0,
     "target": null,
     "shield": 0
    },
    {
     "type": "dragma_skelesoldier",
     "x": 5,
     "y": 5,
     "hp": 70,
     "maxHp": 70,
     "phase": "charge",
     "turns": 1,
     "target": {
      "x": 5,
      "y": 4
     },
     "shield": 0
    },
    {
     "type": "lobcap",
     "x": 5,
     "y": 1,
     "hp": 30,
     "maxHp": 30,
     "phase": "charge",
     "turns": 3,
     "target": null,
     "shield": 0
    }
   ],
   "objects": [
    {
     "type": "stairs",
     "x": 4,
     "y": 1
    }
   ],
   "pickups": [],
   "traps": [],
   "cues": [
    {
     "x": 4,
     "y": 4,
     "kind": "target"
    },
    {
     "x": 5,
     "y": 4,
     "kind": "target"
    },
    {
     "x": 6,
     "y": 5,
     "kind": "aoe"
    },
    {
     "x": 4,
     "y": 5,
     "kind": "aoe"
    },
    {
     "x": 5,
     "y": 6,
     "kind": "aoe"
    }
   ],
   "options": [
    {
     "id": "up",
     "kind": "move",
     "label": "Step up",
     "sub": "",
     "verdict": "best",
     "dmg": 0,
     "energyAfter": 13,
     "kills": false,
     "explain": "Step up and you are out of the bat's dash and outside the soldier's strike. 0 damage, 13 Energy, still alive on floor 9."
    },
    {
     "id": "left",
     "kind": "attack",
     "label": "Attack ←",
     "sub": "kills",
     "verdict": "lethal",
     "dmg": 22,
     "energyAfter": 0,
     "kills": true,
     "explain": "You kill the bat (11 HP vs 24 ATK) and its dash never lands, but the soldier's strike still lands for ~22 on your 14 Energy. Run over, with one kill."
    },
    {
     "id": "right",
     "kind": "blocked",
     "label": "Right",
     "sub": "wall",
     "verdict": "blocked",
     "dmg": 0,
     "energyAfter": 14,
     "kills": false,
     "explain": "That is a wall. You do not move, and both wind-ups still cover your tile."
    },
    {
     "id": "down",
     "kind": "attack",
     "label": "Attack ↓",
     "sub": "HP 70",
     "verdict": "lethal",
     "dmg": 37,
     "energyAfter": 0,
     "kills": false,
     "explain": "70 HP is three swings away, so nothing is stopped and you stay inside the soldier's strike and the bat's dash line for ~36. Run over."
    },
    {
     "id": "pass",
     "kind": "pass",
     "label": "Wait",
     "sub": "",
     "verdict": "lethal",
     "dmg": 37,
     "energyAfter": 0,
     "kills": false,
     "explain": "Pass turn costs 1 Energy and you stay inside both. ~36 incoming on 14 Energy: run over."
    }
   ],
   "answer": "up",
   "reality": "What actually happened: the player stepped up and both attacks landed on an empty tile. 13 Energy, run continues.",
   "lesson": "A kill stops one enemy's attack and nothing else.",
   "_src": {
    "file": "run-cmu7hcndt001agm0aomz5e5fm.jsonl",
    "turn": 1269,
    "floor": 9,
    "weather": "heatwave",
    "room": null
   }
  },
  {
   "id": "p10",
   "title": "One Shot, Zero Energy",
   "hook": "Floor 6, 62 Energy, Blizzard active: an Armored skeleton directly below has its strike aimed at your tile, a 2-HP Blue frog on your left is winding up at someone else, and the spikes above you rise this turn.",
   "mechanic": "Single Shot",
   "mechanicNote": "Single Shot deals 25 to the first enemy in a line and costs no Energy, and a kill from range stops a wind-up exactly like a melee kill does. A hit that does not kill stops nothing. Only one enemy here is aimed at you.",
   "floor": 6,
   "energy": 62,
   "maxEnergy": 114,
   "atk": 19,
   "weather": "blizzard",
   "items": [
    "single_shot"
   ],
   "board": {
    "w": 11,
    "h": 9,
    "tiles": [
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2,
      2
     ],
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2
     ],
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2
     ],
     [
      1,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      2
     ],
     [
      1,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      0,
      0,
      0
     ],
     [
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
     ],
     [
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
     ],
     [
      1,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      0,
      0,
      2
     ],
     [
      1,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      2
     ]
    ]
   },
   "player": {
    "x": 5,
    "y": 4
   },
   "enemies": [
    {
     "type": "skelesoldier",
     "x": 5,
     "y": 5,
     "hp": 22,
     "maxHp": 60,
     "phase": "charge",
     "turns": 1,
     "target": {
      "x": 5,
      "y": 4
     },
     "shield": 0
    },
    {
     "type": "frogspawn",
     "x": 4,
     "y": 3,
     "hp": 80,
     "maxHp": 80,
     "phase": "idle",
     "turns": 0,
     "target": null,
     "shield": 2
    },
    {
     "type": "frogglet",
     "x": 3,
     "y": 3,
     "hp": 2,
     "maxHp": 2,
     "phase": "idle",
     "turns": 0,
     "target": null,
     "shield": 0
    },
    {
     "type": "frogglet",
     "x": 4,
     "y": 4,
     "hp": 2,
     "maxHp": 2,
     "phase": "charge",
     "turns": 2,
     "target": {
      "x": 3,
      "y": 4
     },
     "shield": 0
    }
   ],
   "objects": [],
   "pickups": [
    {
     "type": "treasure",
     "x": 2,
     "y": 4,
     "frozen": 1
    },
    {
     "type": "small_energy_orb",
     "x": 4,
     "y": 4,
     "frozen": 0
    }
   ],
   "traps": [
    {
     "type": "spike",
     "x": 4,
     "y": 5
    },
    {
     "type": "spike",
     "x": 5,
     "y": 3
    },
    {
     "type": "spike",
     "x": 1,
     "y": 7
    }
   ],
   "cues": [
    {
     "x": 5,
     "y": 4,
     "kind": "target"
    },
    {
     "x": 6,
     "y": 5,
     "kind": "aoe"
    },
    {
     "x": 4,
     "y": 5,
     "kind": "aoe"
    },
    {
     "x": 5,
     "y": 6,
     "kind": "aoe"
    },
    {
     "x": 3,
     "y": 4,
     "kind": "target"
    }
   ],
   "options": [
    {
     "id": "up",
     "kind": "move",
     "label": "Step up",
     "sub": "",
     "verdict": "bad",
     "dmg": 7,
     "energyAfter": 54,
     "kills": false,
     "explain": "Stepping up puts you on spikes as they rise: ~7 damage plus 1 Energy for the move. You do leave the strike, at a price the shot would not cost."
    },
    {
     "id": "left",
     "kind": "attack",
     "label": "Attack ←",
     "sub": "kills",
     "verdict": "bad",
     "dmg": 12,
     "energyAfter": 50,
     "kills": true,
     "explain": "The Blue frog dies to one swing, but it was never aiming at you. The skeleton's strike lands for ~12 while you take a kill that does not stop it."
    },
    {
     "id": "right",
     "kind": "blocked",
     "label": "Right",
     "sub": "wall",
     "verdict": "blocked",
     "dmg": 0,
     "energyAfter": 62,
     "kills": false,
     "explain": "That is a wall. You do not move, and the strike is still aimed at you."
    },
    {
     "id": "down",
     "kind": "attack",
     "label": "Attack ↓",
     "sub": "HP 22",
     "verdict": "bad",
     "dmg": 12,
     "energyAfter": 50,
     "kills": false,
     "explain": "19 ATK into 22 HP leaves the skeleton alive on 3, so nothing is stopped. Its strike lands on you for ~12."
    },
    {
     "id": "pass",
     "kind": "pass",
     "label": "Wait",
     "sub": "",
     "verdict": "bad",
     "dmg": 12,
     "energyAfter": 49,
     "kills": false,
     "explain": "Pass turn costs 1 Energy and the strike lands for ~12. Nothing gained."
    },
    {
     "id": "item",
     "kind": "item",
     "label": "Single Shot ↓",
     "sub": "",
     "verdict": "best",
     "dmg": 0,
     "energyAfter": 62,
     "kills": false,
     "explain": "Single Shot down: 25 into 22 HP kills the skeleton from range, its strike never lands, 0 damage, 0 Energy. The only enemy aimed at you is dead and it cost nothing."
    }
   ],
   "answer": "item",
   "reality": "What actually happened: the player killed the Blue frog and took 12 from the Armored skeleton.",
   "lesson": "A Single Shot that kills stops the hit for free; a melee hit that does not kill stops nothing.",
   "_src": {
    "file": "run-cmu6chvxe000wgm0a7lefanhk.jsonl",
    "turn": 654,
    "floor": 6,
    "weather": "blizzard",
    "room": null
   }
  },
  {
   "id": "p06",
   "title": "No Safe Tile",
   "hook": "Floor 9, nearly full Energy, Heatwave with Mirage active so attack charge timing is unpredictable, and no safe tile: a 9-HP Dragma Bat on your left, a second Dragma Bat two tiles below with a dash lined up on your column, and a Skeleton archer above with an arrow lined up down it.",
   "mechanic": "No safe tile",
   "mechanicNote": "Bats dash along a straight line and hit everything on it; archers fire arrows along their row or column. A kill stops only the killed enemy's attack. When no tile is safe, the right action is the one that costs the least Energy.",
   "floor": 9,
   "energy": 126,
   "maxEnergy": 130,
   "atk": 26,
   "weather": "heatwave",
   "items": [
    "pogo_stick"
   ],
   "board": {
    "w": 11,
    "h": 9,
    "tiles": [
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
     ],
     [
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1
     ],
     [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1
     ],
     [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1
     ],
     [
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1
     ],
     [
      1,
      1,
      1,
      1,
      0,
      0,
      1,
      1,
      1,
      1,
      1
     ],
     [
      1,
      1,
      1,
      1,
      0,
      0,
      1,
      1,
      1,
      1,
      1
     ],
     [
      1,
      1,
      1,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1
     ],
     [
      1,
      1,
      1,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      2
     ]
    ]
   },
   "player": {
    "x": 5,
    "y": 4
   },
   "enemies": [
    {
     "type": "dragma_bat",
     "x": 5,
     "y": 6,
     "hp": 35,
     "maxHp": 35,
     "phase": "charge",
     "turns": 1,
     "target": {
      "x": 5,
      "y": 5
     },
     "shield": 0
    },
    {
     "type": "skelearcher",
     "x": 5,
     "y": 1,
     "hp": 20,
     "maxHp": 20,
     "phase": "charge",
     "turns": 2,
     "target": null,
     "shield": 0
    },
    {
     "type": "dragma_skelesoldier",
     "x": 4,
     "y": 2,
     "hp": 18,
     "maxHp": 70,
     "phase": "idle",
     "turns": 0,
     "target": null,
     "shield": 0
    },
    {
     "type": "dragma_bat",
     "x": 4,
     "y": 4,
     "hp": 9,
     "maxHp": 35,
     "phase": "charge",
     "turns": 1,
     "target": {
      "x": 4,
      "y": 4
     },
     "shield": 0
    },
    {
     "type": "ghost1",
     "x": 4,
     "y": 3,
     "hp": 0,
     "maxHp": 0,
     "phase": "idle",
     "turns": 0,
     "target": null,
     "shield": 0
    }
   ],
   "objects": [
    {
     "type": "pot",
     "x": 5,
     "y": 3
    },
    {
     "type": "pot",
     "x": 3,
     "y": 4
    },
    {
     "type": "pot",
     "x": 2,
     "y": 4
    }
   ],
   "pickups": [
    {
     "type": "treasure",
     "x": 4,
     "y": 4,
     "frozen": 0
    }
   ],
   "traps": [
    {
     "type": "spike",
     "x": 5,
     "y": 2
    }
   ],
   "cues": [
    {
     "x": 5,
     "y": 5,
     "kind": "target"
    },
    {
     "x": 4,
     "y": 4,
     "kind": "target"
    }
   ],
   "options": [
    {
     "id": "up",
     "kind": "break",
     "label": "Smash ↑",
     "sub": "",
     "verdict": "bad",
     "dmg": 36,
     "energyAfter": 90,
     "kills": false,
     "explain": "Smashing the pot costs 0 Energy, but you stay on the column with both dashes and the arrow aimed at you. ~36."
    },
    {
     "id": "left",
     "kind": "attack",
     "label": "Attack ←",
     "sub": "kills",
     "verdict": "bad",
     "dmg": 25,
     "energyAfter": 101,
     "kills": true,
     "explain": "Kills the 9-HP bat and stops its dash, but you are still on the other bat's dash line with the archer's arrow coming down the same column. ~25 between them."
    },
    {
     "id": "right",
     "kind": "move",
     "label": "Step right",
     "sub": "",
     "verdict": "best",
     "dmg": 11,
     "energyAfter": 114,
     "kills": false,
     "explain": "Step right and you are off the column and out of the archer's line. One dash still hits you for ~11, and that is the cheapest turn on the board."
    },
    {
     "id": "down",
     "kind": "move",
     "label": "Step down",
     "sub": "",
     "verdict": "bad",
     "dmg": 25,
     "energyAfter": 100,
     "kills": false,
     "explain": "Stepping down moves you toward the 35-HP bat, still on its dash line, still under the archer. ~25."
    },
    {
     "id": "pass",
     "kind": "pass",
     "label": "Wait",
     "sub": "",
     "verdict": "bad",
     "dmg": 36,
     "energyAfter": 89,
     "kills": false,
     "explain": "Pass turn: 1 Energy, still on the column, still next to the 9-HP bat. ~36."
    }
   ],
   "answer": "right",
   "reality": "What actually happened: the player killed the 9-HP bat and still took 12.",
   "lesson": "When no tile is safe, pick the action that loses the least Energy.",
   "_src": {
    "file": "run-cmu6zv1jd006ugm0923sl08q6.jsonl",
    "turn": 1352,
    "floor": 9,
    "weather": "heatwave",
    "room": null
   }
  },
  {
   "id": "p03",
   "title": "Two Energy Left",
   "hook": "Floor 8, 2 Energy, Heatwave with Mirage active so attack charge timing is unpredictable: a Dragma Chump is about to strike your tile from the right and a second one is winding up from below.",
   "mechanic": "Two Energy left",
   "mechanicNote": "Energy is your life force and a move costs 1, so at 2 Energy any hit ends the run. An energy orb restores Energy the moment you step on it, and a kill stops only that enemy's attack.",
   "floor": 8,
   "energy": 2,
   "maxEnergy": 126,
   "atk": 24,
   "weather": "heatwave",
   "items": [
    "single_shot",
    "pogo_stick"
   ],
   "board": {
    "w": 11,
    "h": 9,
    "tiles": [
     [
      2,
      2,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2,
      2
     ],
     [
      2,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2
     ],
     [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2
     ],
     [
      1,
      1,
      1,
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      2
     ],
     [
      0,
      0,
      0,
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      1
     ],
     [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1
     ],
     [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      2
     ],
     [
      0,
      0,
      0,
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      2
     ],
     [
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2
     ]
    ]
   },
   "player": {
    "x": 5,
    "y": 4
   },
   "enemies": [
    {
     "type": "dragma_skelechump",
     "x": 6,
     "y": 4,
     "hp": 18,
     "maxHp": 50,
     "phase": "charge",
     "turns": 1,
     "target": {
      "x": 5,
      "y": 4
     },
     "shield": 0
    },
    {
     "type": "dragma_skelechump",
     "x": 5,
     "y": 5,
     "hp": 34,
     "maxHp": 50,
     "phase": "charge",
     "turns": 2,
     "target": {
      "x": 5,
      "y": 4
     },
     "shield": 0
    },
    {
     "type": "dragma_skelechump",
     "x": 4,
     "y": 5,
     "hp": 34,
     "maxHp": 50,
     "phase": "idle",
     "turns": 0,
     "target": null,
     "shield": 0
    },
    {
     "type": "dragma_skelesoldier",
     "x": 5,
     "y": 6,
     "hp": 42,
     "maxHp": 70,
     "phase": "idle",
     "turns": 0,
     "target": null,
     "shield": 0
    },
    {
     "type": "dragma_skelechump",
     "x": 3,
     "y": 5,
     "hp": 50,
     "maxHp": 50,
     "phase": "idle",
     "turns": 0,
     "target": null,
     "shield": 0
    }
   ],
   "objects": [
    {
     "type": "pot",
     "x": 8,
     "y": 4
    },
    {
     "type": "pot",
     "x": 6,
     "y": 6
    },
    {
     "type": "pot",
     "x": 9,
     "y": 5
    },
    {
     "type": "pot",
     "x": 9,
     "y": 7
    },
    {
     "type": "crate",
     "x": 8,
     "y": 3
    },
    {
     "type": "chest",
     "x": 7,
     "y": 6
    },
    {
     "type": "corn_stalk",
     "x": 7,
     "y": 4
    }
   ],
   "pickups": [
    {
     "type": "golden_corn",
     "x": 6,
     "y": 5,
     "frozen": 0
    },
    {
     "type": "treasure",
     "x": 6,
     "y": 4,
     "frozen": 0
    },
    {
     "type": "marble",
     "x": 6,
     "y": 3,
     "frozen": 0
    },
    {
     "type": "large_energy_orb",
     "x": 5,
     "y": 3,
     "frozen": 0
    },
    {
     "type": "treasure",
     "x": 5,
     "y": 3,
     "frozen": 0
    }
   ],
   "traps": [
    {
     "type": "spike",
     "x": 7,
     "y": 7
    },
    {
     "type": "spike",
     "x": 9,
     "y": 3
    }
   ],
   "cues": [
    {
     "x": 5,
     "y": 4,
     "kind": "target"
    }
   ],
   "options": [
    {
     "id": "up",
     "kind": "move",
     "label": "Step up",
     "sub": "pick up",
     "verdict": "best",
     "dmg": 0,
     "energyAfter": 19,
     "kills": false,
     "explain": "Step onto the energy orb: +17 Energy, and that tile is outside every wind-up on the board. You go from 2 to 19 with Treasure on that tile."
    },
    {
     "id": "left",
     "kind": "blocked",
     "label": "Left",
     "sub": "wall",
     "verdict": "blocked",
     "dmg": 0,
     "energyAfter": 2,
     "kills": false,
     "explain": "That is a wall. You do not move, still on 2 Energy with a strike about to land."
    },
    {
     "id": "right",
     "kind": "attack",
     "label": "Attack →",
     "sub": "kills",
     "verdict": "lethal",
     "dmg": 22,
     "energyAfter": 0,
     "kills": true,
     "explain": "24 ATK into 18 HP kills it and stops its attack, but under Mirage the second chump can strike this turn, and at 2 Energy on its target tile that is run over. A risk with nothing to gain."
    },
    {
     "id": "down",
     "kind": "attack",
     "label": "Attack ↓",
     "sub": "HP 34",
     "verdict": "lethal",
     "dmg": 43,
     "energyAfter": 0,
     "kills": false,
     "explain": "Hitting the 34-HP chump does not kill it, and the 18-HP one strikes you for ~22. On 2 Energy that is run over."
    },
    {
     "id": "pass",
     "kind": "pass",
     "label": "Wait",
     "sub": "",
     "verdict": "lethal",
     "dmg": 43,
     "energyAfter": 0,
     "kills": false,
     "explain": "Pass turn costs 1 Energy, you sit on 1, and the chump strikes you. Run over."
    },
    {
     "id": "item",
     "kind": "item",
     "label": "Single Shot →",
     "sub": "",
     "verdict": "lethal",
     "dmg": 22,
     "energyAfter": 0,
     "kills": false,
     "explain": "Single Shot right kills the 18-HP chump and stops its attack, but under Mirage the 34-HP chump below can strike this turn, and you are still on 2 Energy in its target tile. Run over."
    }
   ],
   "answer": "up",
   "reality": "What actually happened: the player stepped up, took the energy orb, went from 2 to 19 Energy, and finished the run.",
   "lesson": "At 2 Energy, take the energy orb that sits outside every wind-up.",
   "_src": {
    "file": "run-cmu6yysdx002agm0acrlcz4cj.jsonl",
    "turn": 1043,
    "floor": 8,
    "weather": "heatwave",
    "room": null
   }
  }
 ]
};
